Bump release workflow to match the template in the tooling-project-assets repository
arduino/nicla-sense-me-fw pull request #117
Opened 2023-11-22 15:11 UTC by MatteoPologruto

### Description
An excellent tool named [gon](https://github.com/mitchellh/gon) was used to perform the notarization.
the latest stable release of gon uses the altool command-line utility for notarization:
https://github.com/mitchellh/gon/blob/v0.2.5/notarize/upload.go#L41

Using altool for notarization is now deprecated by Apple and support for notarization via this tool is scheduled to be disabled 2023-11-01:
https://developer.apple.com/news/?id=y5mjxqmn

Furthermore, gon was archived.

I switched to https://github.com/Bearer/gon that has included https://github.com/mitchellh/gon/pull/72, hoping the maintainers will take the responsibility of maintaining the project.
I added also AC_PROVIDER env var which is mandatory with the new notarytool.

Overall, the workflow was bumped to match the [template](https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/release-go-task.yml) in the `tooling-project-assets` repository.

### Pull request type

    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Breaking change

2023-11-23 14:29 UTC, umbynos commented on .github/workflows/release-go-task.yml
> +          EOF
Since we hare adding this here let's remove https://github.com/arduino/nicla-sense-me-fw/blob/main/gon.config.hcl

2023-11-23 14:35 UTC, umbynos requested changes
Since so much stuff was changed I would try a release of this on your fork

2023-11-28 17:15 UTC, MatteoPologruto commented on DistTasks.yml
> +  GO_VERSION: "1.17.8"
I decided not to bump the GO version, it is out of the scope of this PR.

2023-11-28 17:16 UTC, MatteoPologruto commented
Test release: https://github.com/MatteoPologruto/nicla-sense-me-fw/releases/tag/9.9.9

2023-11-28 17:16 UTC, MatteoPologruto commented on .github/workflows/release-go-task.yml
> +          AC_PROVIDER: ${{ secrets.AC_PROVIDER }}
I don't have access to this repository's secrets.

2023-11-29 09:04 UTC, umbynos commented on .github/workflows/release-go-task.yml
> +          AC_PROVIDER: ${{ secrets.AC_PROVIDER }}
I added it

2023-11-29 16:25 UTC, merged