[AE-4] Remove Unisense, and correct ESLOV caps in readme
arduino/nicla-sense-me-fw pull request #81
Opened 2023-03-07 06:46 UTC by aliphys

### Description

Remove mention of Unisense and unify capitalisation of ESLOV in `readme.md`

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Breaking change

2023-03-07 06:55 UTC, per1234 requested changes

2023-03-07 06:55 UTC, per1234 commented on README.md
> +- [Nicla](#nicla)
I don't think it makes sense to add the document title as a section in the ToC

2023-03-07 13:45 UTC, aliphys commented on README.md
> +- [Nicla](#nicla)
This was here from before. I haven't added this as part of the PR.

2023-03-07 13:46 UTC, aliphys commented on README.md
> +- [Nicla](#nicla)
```suggestion
```

2023-03-09 13:23 UTC, aliphys commented
@per1234 Can you merge into `main`? I do not have write access.

2023-03-09 13:33 UTC, merged