[AE-28] API documentation for the BHY2 library
arduino/nicla-sense-me-fw pull request #86
Opened 2023-03-29 08:57 UTC by aliphys

### Description

- Describe library functionality in Readme.md
- Add class descriptions for Arduino developed header files based on mbedOS style -> https://os.mbed.com/handbook/API-Documentation#how-to-add-documentation-to-your-own

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Breaking change

2023-03-30 01:38 UTC, per1234 requested changes
The usage and examples documentation should be placed in `Arduino_BHY2/docs/readme.md` so it will be automatically published on the library's reference page:

https://www.arduino.cc/reference/en/libraries/arduino_bhy2/

You can see an example of the library reference system here:
https://github.com/arduino-libraries/Servo/tree/master/docs

The automatically published content on the reference page:
https://www.arduino.cc/reference/en/libraries/servo/#usage

2023-03-30 04:43 UTC, per1234 requested changes

2023-03-30 04:43 UTC, per1234 commented on Arduino_BHY2/docs/README.md
The library reference generation system requires the file to be named exactly `readme.md` (note the different case).

2023-03-30 04:43 UTC, per1234 commented on Arduino_BHY2/docs/README.md
> +- [StandaloneFlashStorage](examples/StandaloneFlashStorage/StandaloneFlashStorage.ino) : Read motion, temperature and gas data and send over and save on Flash storage
```suggestion
- [App](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/App/App.ino) : Control Nicla Sense ME from an external device acting as a host via I2C or ESLOV
- [AppLowDelay](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/AppLowDelay/AppLowDelay.ino) : Control Nicla Sense ME from an external device acting as a host via I2C or ESLOV with a lower delay
- [BHYFirmwareUpdate](https://github.com/arduino-libraries/Arduino_BHY2/tree/main/examples/BHYFirmwareUpdate) : Update ANNA-B112 and BHI260 firmware
- [Fail_Safe_flasher](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/Fail_Safe_flasher/Fail_Safe_flasher.ino) : Fail Safe flashing of a RGB blink sketch
- [ReadSensorConfiguration](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/ReadSensorConfiguration/ReadSensorConfiguration.ino) : Read motion, temperature and gas data and send over Serial
- [ShowSensorList](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/ShowSensorList/ShowSensorList.ino) : List sensors of the Nicla Sense ME board
- [Standalone](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/Standalone/Standalone.ino) : Read motion, temperature and gas data and send over Serial
- [StandaloneFlashStorage](https://github.com/arduino-libraries/Arduino_BHY2/blob/main/examples/StandaloneFlashStorage/StandaloneFlashStorage.ino) : Read motion, temperature and gas data and send over and save on Flash storage 
```

For viewing the content on GitHub, the links could have been adjusted to the Markdown file's new location by adding a `../`, like this:

```markdown
[App](../examples/App/App.ino) : Control Nicla Sense ME from an external device acting as a host via I2C or ESLOV
```
However, that still won't result in a working link in the library reference page.

The convention is to link to the tutorial page for each example. Unfortunately it looks like the tutorials were not written for the library. So I think the only option is to use absolute links to the example files in the library repository.

2023-03-30 04:43 UTC, per1234 commented on Arduino_BHY2/src/Arduino_BHY2.h
> +   * @brief Check existance of sensor
```suggestion
   * @brief Check existence of sensor
```

Misspelling

2023-03-30 04:43 UTC, per1234 commented on Arduino_BHY2/src/Arduino_BHY2.h
> +   * @brief Parse XYZ cartesian data
```suggestion
   * @brief Parse XYZ Cartesian data
```

"Cartesian" is capitalized because it is derived from a proper noun (René Descartes).

References:

- https://style.mla.org/scientific-laws-theories-and-terms/
- https://en.wikipedia.org/wiki/Cartesian_coordinate_system

2023-03-30 04:43 UTC, per1234 commented on Arduino_BHY2/src/BLEHandler.h
> +   * @brief Poll data over bluetooth and read data to FIFO buffer.
```suggestion
   * @brief Poll data over Bluetooth and read data to FIFO buffer.
```

"Bluetooth" is a proper noun.

Reference: https://en.wikipedia.org/wiki/Bluetooth

2023-03-30 04:58 UTC, per1234 requested changes

2023-03-30 04:58 UTC, per1234 commented on Arduino_BHY2/README.md
> +See [docs/README.md](docs/README.md) for usage and examples.
```suggestion
See [docs/readme.md](docs/readme.md) for usage and examples.
```
Update link to reflect changed filename.

2023-03-30 05:05 UTC, per1234 approved these changes
Thanks Ali!

2023-03-30 05:15 UTC, aliphys commented
Can you merge to main? Obtaining write access permission is in progress. cc @sebromero

2023-03-30 05:30 UTC, per1234 commented
I do have the permissions to merge, but I'm not very much involved in this project so I should give the more involved parties the opportunity to review the PR.

2023-03-30 08:40 UTC, merged

2023-05-05 16:07 UTC, sebromero reviewed
@aliphys I added questions where I think we need to clarify the documentation. Two general things:
- Let's use just one `@return` flag as specified in our documentation styleguide.
- The extern keyword is to let the compiler know about global variables. So other files that use that header file can access the variable, but it only needs to be initialized once in one of the source files. Saying that the corresponding variable can be externally linked in the user sketch is not really correct in our case.

2023-05-05 16:07 UTC, sebromero commented on Arduino_BHY2/src/EslovHandler.h
> +   * @brief Nicla Sense ME is mounted as a Shield
What does that function do? Reconfigure pins?

2023-05-05 16:07 UTC, sebromero commented on Arduino_BHY2Host/src/Arduino_BHY2Host.h
> +
What happened to the dual mode? How is this enum used?

2023-05-05 16:07 UTC, sebromero reviewed
@aliphys I added questions where I think we need to clarify the documentation. Two general things:
- Let's use just one `@return` flag as specified in our documentation styleguide.
- The extern keyword is to let the compiler know about global variables. So other files that use that header file can access the variable, but it only needs to be initialized once in one of the source files. Saying that the corresponding variable can be externally linked in the user sketch is not really correct in our case.