[AE-51] Add documentation for BHY2Host
arduino/nicla-sense-me-fw pull request #93
Opened 2023-04-18 06:23 UTC by aliphys

### Description

- Add in-code documentation for BHY2Host classes
    - Arduino_BHY2Host
    - BLEHandler
    - EslovHandler

### Pull request type

    [ ] Fix
    [x ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Breaking change

2023-06-07 14:08 UTC, sebromero requested changes

2023-06-07 14:08 UTC, sebromero commented on Arduino_BHY2Host/src/EslovHandler.h
> +   * @brief Request data from the Nicla board
This is for a specific sensor, right? So do I need to pass the sensor ID or how does this work?

2023-06-07 14:08 UTC, sebromero commented on Arduino_BHY2Host/src/EslovHandler.h
> +   * @return false  Request unsuccessful
Transmission error only or also configuration error?

2023-06-07 14:08 UTC, sebromero commented on Arduino_BHY2Host/src/EslovHandler.h
> +   * @brief Request long data from the Nicla board
Same comment as for requestSensorData()

2023-06-07 14:08 UTC, sebromero commented on Arduino_BHY2Host/src/EslovHandler.h
> +   * @brief Nicla Sense ME is mounted as a Shield
What does the function do? Does it set some pins, change some configuration, ...?

2023-06-19 18:54 UTC, aliphys commented
Closing PR, changes are in https://github.com/arduino/nicla-sense-me-fw/pull/104

2023-06-19 18:54 UTC, closed without merging